services:
  provider:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_HOST: ${APP_HOST:-0.0.0.0}
      APP_PORT: ${APP_PORT:-8000}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      REQUEST_TIMEOUT_SECONDS: ${REQUEST_TIMEOUT_SECONDS:-20}
      AUDIOBOOKSHELF_AUTH_TOKEN: ${AUDIOBOOKSHELF_AUTH_TOKEN:-}
      SCRAPER_USER_AGENT: ${SCRAPER_USER_AGENT:-}
    restart: unless-stopped
#     networks: # Use the existing network created by Audiobookshelf
#       - audiobookshelf_default

# networks: # Use the existing network created by Audiobookshelf
#   audiobookshelf_default:
#     external: true